package com.peatral.archinumbuilds.client.Models;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelArmor extends ModelBiped {
	ModelRenderer MGNodLeft;
	ModelRenderer MGNodRight;
	ModelRenderer MGBack;
	ModelRenderer MGBack2;
	ModelRenderer MGBackThingLeft;
	ModelRenderer MGBackThingRight;
	ModelRenderer MGBackThingConnectorRight;
	ModelRenderer MGBackThingConnectorLeft;
	ModelRenderer MGBackConnectorLeft;
	ModelRenderer MGBackConnectorRight;
	ModelRenderer HelmetTop;
	ModelRenderer HelmetBack;
	ModelRenderer HelmetLeft1;
	ModelRenderer HelmetLeft2;
	ModelRenderer HelmetLeftTop1;
	ModelRenderer HelmetLeftTop2;
	ModelRenderer HelmetRight1;
	ModelRenderer HelmetRight2;
	ModelRenderer HelmetRightTop1;
	ModelRenderer HelmetRightTop2;
	ModelRenderer HelmetLeftDown2;
	ModelRenderer HelmetRightDown2;
	ModelRenderer HelmetLeftDown1;
	ModelRenderer HelmetRightDown1;

	public ModelArmor() {
		textureWidth = 64;
		textureHeight = 64;

		MGNodLeft = new ModelRenderer(this, 32, 0);
		MGNodLeft.addBox(1F, 9F, 1.5F, 2, 2, 1);
		MGNodLeft.setRotationPoint(0F, 0F, 0F);
		MGNodLeft.setTextureSize(64, 64);
		MGNodLeft.mirror = true;
		setRotation(MGNodLeft, 0F, 0F, 0F);
		MGNodRight = new ModelRenderer(this, 32, 0);
		MGNodRight.addBox(-3F, 9F, 1.5F, 2, 2, 1);
		MGNodRight.setRotationPoint(0F, 0F, 0F);
		MGNodRight.setTextureSize(64, 64);
		MGNodRight.mirror = true;
		setRotation(MGNodRight, 0F, 0F, 0F);
		MGBack = new ModelRenderer(this, 38, 0);
		MGBack.addBox(-1.5F, 10F, 3F, 3, 2, 3);
		MGBack.setRotationPoint(0F, 0F, 0F);
		MGBack.setTextureSize(64, 64);
		MGBack.mirror = true;
		setRotation(MGBack, 0F, 0F, 0F);
		MGBack2 = new ModelRenderer(this, 32, 3);
		MGBack2.addBox(-0.5F, 10.86667F, 5.3F, 1, 1, 2);
		MGBack2.setRotationPoint(0F, 0F, 0F);
		MGBack2.setTextureSize(64, 64);
		MGBack2.mirror = true;
		setRotation(MGBack2, 0F, 0F, 0F);
		MGBackThingLeft = new ModelRenderer(this, 50, 6);
		MGBackThingLeft.addBox(2F, 8.5F, 3.5F, 2, 5, 5);
		MGBackThingLeft.setRotationPoint(0F, 0F, 0F);
		MGBackThingLeft.setTextureSize(64, 64);
		MGBackThingLeft.mirror = true;
		setRotation(MGBackThingLeft, 0F, 0.2F, 0F);
		MGBackThingRight = new ModelRenderer(this, 43, 6);
		MGBackThingRight.addBox(-4F, 8.5F, 3.5F, 2, 5, 5);
		MGBackThingRight.setRotationPoint(0F, 0F, 0F);
		MGBackThingRight.setTextureSize(64, 64);
		MGBackThingRight.mirror = true;
		setRotation(MGBackThingRight, 0F, -0.2F, 0F);
		MGBackThingConnectorRight = new ModelRenderer(this, 32, 0);
		MGBackThingConnectorRight.addBox(-2.1F, 10.5F, 5.5F, 2, 1, 1);
		MGBackThingConnectorRight.setRotationPoint(0F, 0F, 0F);
		MGBackThingConnectorRight.setTextureSize(64, 64);
		MGBackThingConnectorRight.mirror = true;
		setRotation(MGBackThingConnectorRight, 0F, -0.2F, 0F);
		MGBackThingConnectorLeft = new ModelRenderer(this, 32, 0);
		MGBackThingConnectorLeft.addBox(0.1F, 10.5F, 5.5F, 2, 1, 1);
		MGBackThingConnectorLeft.setRotationPoint(0F, 0F, 0F);
		MGBackThingConnectorLeft.setTextureSize(64, 64);
		MGBackThingConnectorLeft.mirror = true;
		setRotation(MGBackThingConnectorLeft, 0F, 0.2F, 0F);
		MGBackConnectorLeft = new ModelRenderer(this, 40, 5);
		MGBackConnectorLeft.addBox(2.5F, 9F, 3F, 1, 1, 3);
		MGBackConnectorLeft.setRotationPoint(0F, 0F, 0F);
		MGBackConnectorLeft.setTextureSize(64, 64);
		MGBackConnectorLeft.mirror = true;
		setRotation(MGBackConnectorLeft, -0.3F, -0.7F, 0F);
		MGBackConnectorRight = new ModelRenderer(this, 40, 5);
		MGBackConnectorRight.addBox(-3.5F, 9F, 3F, 1, 1, 3);
		MGBackConnectorRight.setRotationPoint(0F, 0F, 0F);
		MGBackConnectorRight.setTextureSize(64, 64);
		MGBackConnectorRight.mirror = true;
		setRotation(MGBackConnectorRight, -0.3F, 0.7F, 0F);
		HelmetTop = new ModelRenderer(this, 0, 33);
		HelmetTop.addBox(-4.5F, -8.5F, -4.5F, 9, 1, 9);
		HelmetTop.setRotationPoint(0F, 0F, 0F);
		HelmetTop.setTextureSize(64, 64);
		HelmetTop.mirror = true;
		setRotation(HelmetTop, 0F, 0F, 0F);
		HelmetBack = new ModelRenderer(this, 37, 33);
		HelmetBack.addBox(-3.5F, -7.5F, 3.5F, 7, 5, 1);
		HelmetBack.setRotationPoint(0F, 0F, 0F);
		HelmetBack.setTextureSize(64, 64);
		HelmetBack.mirror = true;
		setRotation(HelmetBack, 0F, 0F, 0F);
		HelmetLeft1 = new ModelRenderer(this, 0, 44);
		HelmetLeft1.addBox(3.5F, -7.5F, -3.5F, 1, 3, 8);
		HelmetLeft1.setRotationPoint(0F, 0F, 0F);
		HelmetLeft1.setTextureSize(64, 64);
		HelmetLeft1.mirror = true;
		setRotation(HelmetLeft1, 0F, 0F, 0F);
		HelmetLeft2 = new ModelRenderer(this, 19, 44);
		HelmetLeft2.addBox(4F, -6.5F, -1.5F, 1, 3, 3);
		HelmetLeft2.setRotationPoint(0F, 0F, 0F);
		HelmetLeft2.setTextureSize(64, 64);
		HelmetLeft2.mirror = true;
		setRotation(HelmetLeft2, 0F, 0F, 0F);
		HelmetLeftTop1 = new ModelRenderer(this, 28, 44);
		HelmetLeftTop1.addBox(3F, -11F, -3.5F, 1, 3, 2);
		HelmetLeftTop1.setRotationPoint(0F, 0F, 0F);
		HelmetLeftTop1.setTextureSize(64, 64);
		HelmetLeftTop1.mirror = true;
		setRotation(HelmetLeftTop1, -0.7504916F, 0F, 0F);
		HelmetLeftTop2 = new ModelRenderer(this, 19, 51);
		HelmetLeftTop2.addBox(3.5F, -2.8F, 3F, 1, 2, 1);
		HelmetLeftTop2.setRotationPoint(0F, 0F, 0F);
		HelmetLeftTop2.setTextureSize(64, 64);
		HelmetLeftTop2.mirror = true;
		setRotation(HelmetLeftTop2, 2.181662F, 0F, 0F);
		HelmetRight1 = new ModelRenderer(this, 0, 44);
		HelmetRight1.addBox(-4.5F, -7.5F, -3.5F, 1, 3, 8);
		HelmetRight1.setRotationPoint(0F, 0F, 0F);
		HelmetRight1.setTextureSize(64, 64);
		HelmetRight1.mirror = true;
		setRotation(HelmetRight1, 0F, 0F, 0F);
		HelmetRight2 = new ModelRenderer(this, 19, 44);
		HelmetRight2.addBox(4F, -6.5F, -1.5F, 1, 3, 3);
		HelmetRight2.setRotationPoint(0F, 0F, 0F);
		HelmetRight2.setTextureSize(64, 64);
		HelmetRight2.mirror = true;
		setRotation(HelmetRight2, 0F, 3.141593F, 0F);
		HelmetRightTop1 = new ModelRenderer(this, 28, 44);
		HelmetRightTop1.addBox(-4F, -11F, -3.5F, 1, 3, 2);
		HelmetRightTop1.setRotationPoint(0F, 0F, 0F);
		HelmetRightTop1.setTextureSize(64, 64);
		HelmetRightTop1.mirror = true;
		setRotation(HelmetRightTop1, -0.7504916F, 0F, 0F);
		HelmetRightTop2 = new ModelRenderer(this, 19, 51);
		HelmetRightTop2.addBox(-4.5F, -2.8F, 3F, 1, 2, 1);
		HelmetRightTop2.setRotationPoint(0F, 0F, 0F);
		HelmetRightTop2.setTextureSize(64, 64);
		HelmetRightTop2.mirror = true;
		setRotation(HelmetRightTop2, 2.181662F, 0F, 0F);
		HelmetLeftDown2 = new ModelRenderer(this, 19, 51);
		HelmetLeftDown2.addBox(2.7F, -12.3F, -4.5F, 1, 2, 1);
		HelmetLeftDown2.setRotationPoint(0F, 0F, 0F);
		HelmetLeftDown2.setTextureSize(64, 64);
		HelmetLeftDown2.mirror = true;
		setRotation(HelmetLeftDown2, -0.9075712F, 0F, 0F);
		HelmetRightDown2 = new ModelRenderer(this, 19, 51);
		HelmetRightDown2.addBox(-3.7F, -12.3F, -4.5F, 1, 2, 1);
		HelmetRightDown2.setRotationPoint(0F, 0F, 0F);
		HelmetRightDown2.setTextureSize(64, 64);
		HelmetRightDown2.mirror = true;
		setRotation(HelmetRightDown2, -0.9075712F, 0F, 0F);
		HelmetLeftDown1 = new ModelRenderer(this, 28, 44);
		HelmetLeftDown1.addBox(3.7F, -2.6F, -4.5F, 1, 3, 2);
		HelmetLeftDown1.setRotationPoint(0F, 0F, 0F);
		HelmetLeftDown1.setTextureSize(64, 64);
		HelmetLeftDown1.mirror = true;
		setRotation(HelmetLeftDown1, -0.7853982F, 0F, 0F);
		HelmetRightDown1 = new ModelRenderer(this, 28, 44);
		HelmetRightDown1.addBox(-4.7F, -2.6F, -4.5F, 1, 3, 2);
		HelmetRightDown1.setRotationPoint(0F, 0F, 0F);
		HelmetRightDown1.setTextureSize(64, 64);
		HelmetRightDown1.mirror = true;
		setRotation(HelmetRightDown1, -0.7853982F, 0F, 0F);

		this.bipedBody.addChild(MGBack);
		this.bipedBody.addChild(MGBack2);
		this.bipedBody.addChild(MGBackConnectorLeft);
		this.bipedBody.addChild(MGBackConnectorRight);
		this.bipedBody.addChild(MGBackThingConnectorLeft);
		this.bipedBody.addChild(MGBackThingConnectorRight);
		this.bipedBody.addChild(MGBackThingLeft);
		this.bipedBody.addChild(MGBackThingRight);
		this.bipedBody.addChild(MGNodLeft);
		this.bipedBody.addChild(MGNodRight);
		this.bipedHead.addChild(HelmetTop);
		this.bipedHead.addChild(HelmetBack);
		this.bipedHead.addChild(HelmetLeft1);
		this.bipedHead.addChild(HelmetLeft2);
		this.bipedHead.addChild(HelmetRight1);
		this.bipedHead.addChild(HelmetRight2);
		this.bipedHead.addChild(HelmetLeftDown1);
		this.bipedHead.addChild(HelmetLeftDown2);
		this.bipedHead.addChild(HelmetRightDown1);
		this.bipedHead.addChild(HelmetRightDown2);
		this.bipedHead.addChild(HelmetLeftTop1);
		this.bipedHead.addChild(HelmetLeftTop2);
		this.bipedHead.addChild(HelmetRightTop1);
		this.bipedHead.addChild(HelmetRightTop2);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5, Entity ent) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, ent);
		MGNodLeft.render(f5);
		MGNodRight.render(f5);
		MGBack.render(f5);
		MGBack2.render(f5);
		MGBackThingLeft.render(f5);
		MGBackThingRight.render(f5);
		MGBackThingConnectorRight.render(f5);
		MGBackThingConnectorLeft.render(f5);
		MGBackConnectorLeft.render(f5);
		MGBackConnectorRight.render(f5);
		HelmetTop.render(f5);
		HelmetBack.render(f5);
		HelmetLeft1.render(f5);
		HelmetLeft2.render(f5);
		HelmetLeftTop1.render(f5);
		HelmetLeftTop2.render(f5);
		HelmetRight1.render(f5);
		HelmetRight2.render(f5);
		HelmetRightTop1.render(f5);
		HelmetRightTop2.render(f5);
		HelmetLeftDown2.render(f5);
		HelmetRightDown2.render(f5);
		HelmetLeftDown1.render(f5);
		HelmetRightDown1.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
	}

}
